#
# Reference:
# - Docs : https://docs.fluentbit.io/manual/v/1.3/
# - Github : https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit
#

env:
  - name: FLUENTD_HOST
    value: fluentd-aggregator.monitoring.svc
  - name: FLUENTD_PORT
    value: "24224"
flush: 1

config:
  service: |
    [SERVICE]
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        # Parsers_File custom_parsers.conf
        Daemon Off
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Tag kube.*
        Path /var/log/containers/*.log
        parser docker
        DB /var/log/fluentbit_kube.db
        Refresh_Interval  5
        Buffer_Chunk_Size 512k
        Buffer_Max_Size 1024k
        Mem_Buf_Limit 5MB

    # [INPUT]
    #     Name systemd
    #     Tag host.*
    #     Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    #     Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Merge_Log_Key       log_processed
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off
        Buffer_Size         1Mb

    [FILTER]
        Name nest
        Match kube.*
        Wildcard pod_name
        Operation lift
        Nested_under kubernetes

    [FILTER]
        Name        record_modifier
        Match       kube.*
        Remove_key  labels
        Remove_key  container_image
        Remove_key  container_hash
        Remove_key  docker_id
        Remove_key  pod_id

    # [FILTER]
    #     Name        record_modifier
    #     Match       *.*
    #     Remove_key  tag

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name forward
        Match kube.*
        Host ${FLUENTD_HOST}
        Port ${FLUENTD_PORT}
        Retry_Limit False
